FROM alpine:3.2

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update; apk add sl@testing bash

ADD https://gist.githubusercontent.com/diogomonica/40e285ef1e91b2f29409/raw/471969475f814c79fabb0d2b96393760a1ffc012/demo_script.sh /usr/bin/script
RUN chmod +x /usr/bin/script

ENTRYPOINT [ "script" ]
